### ISSUE TITLE
Question about the library

### ISSUE THREAD

**Issue by rpgoldman** [mmontone/schemata#1]
Does the schema language you have used correspond to JSON schema? Or is it a separate thing?  It looks like `schema-from-json-schema` will do that, but I wasn't sure.  Thanks!

**Comment by mmontone** [comment]
Hi. It is a separate thing. This is a library I stripped off from cl-rest-server, a library for developing rest apis.

There's some code for transforming from and to JSON schema, as you say. But it is a reduced version of JSON schema. The parts for simple JSON schemas that may be used in an OpenAPI spec. I wrote that code for reading OpenAPI spec and get schemata schemas from them.

The library works for the general cases, but I think it could be better. I wanted to rewrite it for using CL structures or CLOS for the schemas representation at some point, but I didn't get to.

**Comment by rpgoldman** [comment]
@mmontone I have been trying out schemata.json-schema, but I'm not having a lot of luck.  In particular, a lot of the code for processing the JSON schema assumes that entries in the schema will be strings, but when we read the schema through cl-json, some of those strings are transformed into symbols.

I just used `cl-json` to read the JSON schema file, and maybe that wasn't right?  Did you by any chance read the schema files in some special way instead of using cl-json normally before invoking `schema-from-json-schema`?

I found some issues in $ref parsing, too.  I could share my in-process fork if you are interested.

**Comment by mmontone** [comment]
You are correct, I'm using json library in a non-default way. No good :|

```lisp
JSON-SCHEMA> (let ((json:*identifier-name-to-key* 'identity)
                   (json:*json-identifier-name-to-lisp* 'identity))
               (json:decode-json-from-string *example*))
(("$id" . "https://example.com/person.schema.json")
 ("$schema" . "https://json-schema.org/draft/2020-12/schema")
 ("title" . "Person") ("type" . "object")
 ("properties"
  ("firstName" ("type" . "string")
   ("description" . "The person's first name."))
  ("lastName" ("type" . "string") ("description" . "The person's last name."))
  ("age"
   ("description"
    . "Age in years which must be equal to or greater than zero.")
   ("type" . "integer") ("minimum" . 0))))
JSON-SCHEMA> (schema-from-json-schema *)
(:OBJECT "Person"
 (("firstName" :STRING :EXTERNAL-NAME "firstName" :OPTIONAL T :DOCUMENTATION
   "The person's first name.")
  ("lastName" :STRING :EXTERNAL-NAME "lastName" :OPTIONAL T :DOCUMENTATION
   "The person's last name.")
  ("age" :INTEGER :EXTERNAL-NAME "age" :OPTIONAL T :DOCUMENTATION
   "Age in years which must be equal to or greater than zero."))
 (:DOCUMENTATION NIL))
JSON-SCHEMA> 
```

My only excuse that I marked this as WIP: https://github.com/mmontone/schemata/blob/3251c9c2b35931873e53eb736cdbf090092e36d2/json-schema.lisp#L10

The cl-json library conversions makes things difficult some times. Perhaps a library like yason would have been a better choice. But I can say in retrospect.

**Comment by mmontone** [comment]
Hi, I have some news.

I've rewritten the code base to use CLOS objects as new base for schemas.
I've done this because I think the previous implementation and representation of schemas was too loose. 
As a result of this code for validation and serialization got much simpler, and the parsing of schemas got more robust (schemas are parsed and signal an error if they are malformed).

But this comes with some changes:
- No more keywords for type specs. Only CL symbols. (use `integer` instead of `:integer`).
- To reference other schemas, use the `(schema schema-name)` syntax. Or the `(ref schema-name)`. They are identical.
- To compose lists, use the `(list-of element-schema)` instead of `(:list element-schema)`.

Expect docs and updates soon. You will have to look at the tests.lisp for now.

I apologize for the inconvenience, but now I feel much more confident building on top of this implementation.

**Comment by mmontone** [comment]
Please let me know if you have suggestions to make the implementation better, or more to your liking.

**Comment by mmontone** [comment]
For reference, there's json-schema library: https://github.com/fisxoj/json-schema
